# Generated by Django 2.1.7 on 2020-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistration', '0003_auto_20200804_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
