# Generated by Django 2.1.7 on 2020-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistration', '0004_auto_20200806_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
