# Generated by Django 2.1.7 on 2020-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistration', '0006_auto_20200806_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30),
        ),
    ]
