# Generated by Django 2.1.7 on 2020-08-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistration', '0015_auto_20200809_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Course_applied',
            field=models.CharField(choices=[('Computer Science Engg', 'Computer Science Engg'), ('Electronics and Communication Engg', 'Electronics and Communication Engg'), ('Mechanical Engg', 'Mechanical Engg'), ('Electrical and Electronics Engg', 'Electrical and Electronics Engg'), ('Instrumentation and Control Engg', 'Instrumentation and Control Engg'), ('Chemical Engg', 'Chemical Engg'), ('Metalurgy Engg', 'Metalurgy Engg'), ('Production Engg', 'Production Engg'), ('Civil Engg', 'Civil Engg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='State',
            field=models.CharField(max_length=50),
        ),
    ]
